### ISSUE TITLE
Drag and drop not working when using an iframe inside <VueDragResize> any idea?

### ISSUE THREAD

**Issue by romain130492** [kirillmurashov/vue-drag-resize#157]
Hey
Just wondering how to make the drag and drop feature work when using an iframe,

```js
 <VueDragResize v-if="initedValues" :isActive="true" :w="videoData.width" :h="videoData.height" :x="initedValues.x" :y="initedValues.y" v-on:resizing="resize" v-on:dragging="resize" parentLimitation="true" aspectRatio="true">

        <iframe src="https://google.com" frameborder="0"></iframe>

 </VueDragResize>

```
thx!

**Comment by romain130492** [comment]
Ok, i found a way;)
Using that solution: https://stackoverflow.com/questions/26389950/allow-drag-and-drop-of-an-element-containing-an-iframe


```css
  ::v-deep .content-container:after {
    content: "";
    display: block;
    position: absolute;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
  }


```
