### ISSUE TITLE
Ability to remove outline as shown here:

### ISSUE THREAD

**Issue by sktzofrenic** [kirillmurashov/vue-drag-resize#66]
![image](https://user-images.githubusercontent.com/11902047/59564484-6c779500-9015-11e9-8a85-789ecadd4939.png)

It's very hard to see, but I was wondering if there was an option to remove this outline show in the screenshot? 

Here is the offending css:

```css
.vdr.active:before {
    content: "";
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    outline: 1px dashed #d6d6d6;  <--------------------- here
}
```

I didn't see an option to disable this as a prop, which would be nice. Thanks!
